# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f27e99f13e775e4ef799d2e7dd9b072831ea256c400ed4a60bee18b01931eaabc2cb9104e77a579dc37528e0ddb3ac4f04e3f0ad4055b8d7db2ff5a6b7d89c5

test:
  secret_key_base: be52595b50d4227b57206a6a02ce1a00c35de0ac205f4b3f28fa5d4e56b11f91b863c5ee3a4eaf0e236ede4f26fb46e5c018d3779c18f98c1335a966ef993dfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
